### ISSUE TITLE
Conflicting Copies of Backgrid Filter 0.3.5 are Present in This Repository

### ISSUE THREAD

**Issue by GuyPaddock** [WrenSecurity/wrensec-deps#7]
There are two different versions of Backgrid Filter in this repository:
```
f5b426494d5e4324c29a6a137303fcb8  ./repo/org/forgerock/commons/ui/libs/backgrid-filter/0.3.5/backgrid-filter.min-0.3.5-min.js
9843453abb3ea9d987668bfd48e6e653  ./repo/org/forgerock/commons/ui/libs/backgrid-filter.min/0.3.5/backgrid-filter.min-0.3.5-min.js
```

- The first file matches the actual, official minified version of [version 0.3.5 of Backgrid Filter](https://github.com/cloudflare/backgrid-filter/releases/tag/0.3.5).
- The second file doesn't match any of the official minified versions of Backgrid Filter, but exactly matches the version that ForgeRock is currently distributing with OpenIDM.

The 0.3.5 version is missing the `query` method that OpenIDM and presumably other projects (like OpenAM) depend on. See https://github.com/WrenSecurity/wrenidm/issues/34 for an example of such an issue.

The "right" copy (as far as OpenIDM and ForgeRock are concerned) is in the [wrensec-ui-third-party](https://github.com/WrenSecurity/wrensec-ui-third-party/tree/master/backgrid-filter/0.3.5) repository.

The clearest path forward would be to pull version 0.3.5 completely from the `wrensec-ui-third-party` repository, add the [official 0.3.7 release](https://github.com/cloudflare/backgrid-filter/releases/tag/0.3.7), and then update all Wren projects that use Backgrid Filter to depend on the 0.3.7 version. That guarantees the project has a known good version that's traceable to the source, while including the required functionality.

**Comment by siepkes** [comment]
@GuyPaddock Thanks for reporting this! We are currently working hard to put this repo to rest by deploying all the required deps for DS, AM and IDM to JFrog and Bintray. The goal is to sunset / archive this repo entirely. Since we are getting pretty close to that goal there should be no need for this repo anymore in the nearby future. Therefor I'll leave this issue for now. However if that breaks your workflow i'll still merge PR's that get submitted to fix things.
